on:
  pull_request:
  push: 
  
name: CI 
jobs: 
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install pkg-config cmake libfftw3-dev libchromaprint-dev
      - run: cargo build
      - run: wget https://github.com/acoustid/chromaprint/releases/download/v1.5.1/chromaprint-fpcalc-1.5.1-linux-x86_64.tar.gz -O fpcalc.tar.gz
      - run: tar xvzf fpcalc.tar.gz
      - shell: bash
        run: |
          OUR="$(cargo run --quiet "Auditorium Applause-SoundBible.com-280911206.wav")"
          FPCALC="$(./chromaprint-fpcalc-1.5.1-linux-x86_64/fpcalc "Auditorium Applause-SoundBible.com-280911206.wav" -plain)"
          
          if [ "$OUR" != "$FPCALC" ] ; then
          echo "No match"
          echo
          diff  <(echo "$OUR" ) <(echo "$FPCALC")
          fi
        
